### ISSUE TITLE
Implementering af External API Service

### ISSUE THREAD

**Issue by jk-randers** [Randers-Kommune-Digitalisering/api-service#40]
![Image](https://github.com/Randers-Kommune-Digitalisering/Nexus/assets/146716465/b8200d27-ae29-4f59-a738-e4be58276e56)

```[tasklist]
### Tasks
- [x] base API client
- [x] Nexus  client
- [x] Sbsys  client
- [x] KP  client
- [ ] https://github.com/Randers-Kommune-Digitalisering/Nexus/issues/43
- [ ] Delta  client
- [ ] https://github.com/Randers-Kommune-Digitalisering/Nexus/issues/41
```
