### ISSUE TITLE
Håndtering af ansættelsesbrevfiler fra personalesager

### ISSUE THREAD

**Issue by jk-randers** [Randers-Kommune-Digitalisering/api-service#47]
```[tasklist]
### Tasks
- [x] 1. Itérer på personer, og hent deres personalesager i sbsys
- [x] 2. Itérer over personalesager, og hent ansættelsesfiler
- [x] 3. Læs filer med og uden OCR
- [ ] 4. Sammenlign ansættelsesdato i ansættelsesbrev og sd ansættelse.
```
